### ISSUE TITLE
Process Tree Instead of Process List

### ISSUE THREAD

**Issue by mneverov** [ByNyo/GitTesting#2]
[ps aux](https://github.com/ByNyo/GitTesting/blob/main/Tasks/Process-Thread-Goroutine/QuestionsAndTasks.png) shows process list that look like 
![Screenshot from 2024-09-02 08-12-30](https://github.com/user-attachments/assets/f91eeba1-24eb-418a-ae15-031312e52b74)

Use ps to show parent-child process relations like:
![Screenshot from 2024-09-02 08-13-32](https://github.com/user-attachments/assets/adcf82f0-9770-404d-a2ab-db4e9befae0b)

The output should be similar to [pstree](https://man7.org/linux/man-pages/man1/pstree.1.html).

Extra task: how to wrap words in ps output?

**Comment by ByNyo** [comment]
With `ps axjf` you are able to show what you see in the picture.
The answer to the extra task is `ps -ww axjf`.
