### ISSUE TITLE
Start A Process In Background

### ISSUE THREAD

**Issue by mneverov** [ByNyo/GitTesting#3]
[ctrl+z](https://github.com/ByNyo/GitTesting/blob/main/Tasks/Process-Thread-Goroutine/QuestionsAndTasks.png) works, but imagine you need to start a background job from a makefile. It is possible to use a control operator to run a command in the background. `man bash` might be useful.

Extra task:
start the go app in the background
list all background jobs
bring the background job to the foreground

**Comment by ByNyo** [comment]
Improved it see my results here [here](https://github.com/ByNyo/GitTesting/blob/main/Makefile/Makefile).
